name: comedy
favicon: null
layout_spectrum: 0.035120551474392414
typography_spectrum: 0.32481
title: Comedy Comedy Comedy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#282928'
    - '#acb8be'
    - '#6e6e6e'
    - '#d9d9d9'
  brandStrength: 0.75
  lightness: 0.02595603815279901
  saturation: 0.946329690515995
  rhythmicContrast: 0.28524009324610233
purpose: []
